choir/urls.py
from django.urls import re_path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(pattern_name='events')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
    # re_path(r'^sheets/$', views.sheets, name='sheets'),
    re_path(r'^events/$', views.events, name='events'),
    re_path(r'^wishlist/$', views.wishlist, name='wishlist'),
    re_path(r'^events/(\d+)$', views.event_details, name='event_details'),
    re_path(r'^choir/$', views.choir_details, name='choir_details'),

    re_path(r'^pieces/$', views.search, name='search'),
    re_path(r'^pieces/authors/$', views.authors, name='authors'),
    re_path(r'^pieces/categories/$', views.categories, name='categories'),
    re_path(r'^pieces/(\d+)$', views.piece_detail, name='piece_detail'),

# Depreciated
    re_path(r'^repertoire/search$', views.search, name='repertoire_search'),
    re_path(r'^repertoire/authors/$', views.authors, name='repertoire_authors'),
    re_path(r'^repertoire/categories/$', views.categories, name='repertoire_categories'),
    re_path(r'^repertoire/(\d+)$', views.piece_detail, name='repertoire_piece_detail'),

#     re_path(r'^pieces/(\d+)/upload/main$', views.upload_main, name='upload_main'),
#     re_path(r'^pieces/(\d+)/upload/voice_type/result$', views.upload_voice_type_result, name='upload_voice_type_result'),
#     re_path(r'^pieces/(\d+)/upload/concert$', views.upload_sheet, name='upload_concert'),
     re_path(r'^pieces/(\d+)/upload/practicing_record$', views.upload_practice_recording, name='upload_practice_recording'),
     re_path(r'^pieces/(\d+)/upload/sheet$', views.upload_sheet, name='upload_sheet'),
]

djangochoir/urls.py
"""djangochoir URL Configuration
"""
from django.urls import re_path, include
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^markdownx/', include('markdownx.urls')),
    re_path(r'^xmas/', include('christmas.urls')),
    re_path(r'^', include('choir.urls')),
]

choir/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from datetime import datetime
import unicodedata


def remove_accent_lower(text: str) -> str:
    return unicodedata.normalize('NFKD', text).lower().replace("ø", "o").encode('ASCII', 'ignore').decode('ASCII')


MONTH_NAMES = [
    '', 'január', 'február', 'március', 'április', 'május', 'június',
    'július', 'augusztus', 'szeptember', 'október', 'november', 'december'
]


# import calendar
# MONTH_NAMES = calendar.month_name


class Person(models.Model):
    class Meta:
        verbose_name = "személy"
        verbose_name_plural = "személyek"
        ordering = ["family_name"]

    suffix = models.CharField("előtag", max_length=70, blank=True, default="")
    family_name = models.CharField("családnév", max_length=70)
    given_name = models.CharField("keresztnév", max_length=70)
    NAME_ORDERS = (
        (0, "Western"),
        (1, "Eastern"),
    )
    name_order = models.IntegerField(
        choices=NAME_ORDERS,
    )

    def get_full_name(self):
        if self.name_order == 0:
            first = self.given_name
            second = self.family_name
        elif self.name_order == 1:
            first = self.family_name
            second = self.given_name
        name = f"{first} {second}"
        if self.suffix:
            name = self.suffix + " " + name
        return name

    def get_listed_name(self, bold_family=False):
        if bold_family:
            format_string = "<b>{0.family_name}</b>, {0.given_name}"
        else:
            format_string = "{0.family_name}, {0.given_name}"

        if self.suffix:
            format_string = "{0.suffix} " + format_string
        return format_string.format(self)

    def get_bold_listed_name(self):
        return self.get_listed_name(bold_family=True)

    def __str__(self):
        return self.get_listed_name()


class Member(models.Model):
    DAY_CHOICES = [(i, i) for i in range(1, 32)]
    MONTH_CHOICES = [(i, MONTH_NAMES[i]) for i in range(1, 13)]
    PARTS = (
        ("S", "szoprán"),
        ("A", "alt"),
        ("T", "tenor"),
        ("B", "basszus"),
    )
    name = models.CharField("Név", max_length=200)

    email = models.EmailField("Email", blank=True, null=True)
    phone = models.CharField("Telefonszám", max_length=40, blank=True, null=True)

    birth_month = models.IntegerField("Születési hónap", choices=MONTH_CHOICES)
    birth_day = models.IntegerField("Születési nap", choices=DAY_CHOICES)

    name_month = models.IntegerField("Névnap hónapja", choices=MONTH_CHOICES)
    name_day = models.IntegerField("Névnap napja", choices=DAY_CHOICES)

    part = models.CharField("Szólam", max_length=1, choices=PARTS)

    public_notes = models.TextField("Szöveg a honlapra", max_length=250, blank=True)

    address = models.CharField("Cím", max_length=200)

    image = models.ImageField("Arckép honlapra", blank=True, null=True)

    is_leader = models.BooleanField("Karvezető?", default=False)

    is_active = models.BooleanField(
        "Aktív",
        default=True,
        help_text="Az aktív tagok jelennek meg a bemutatkozóoldalon."
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "kórustag"
        verbose_name_plural = "kórustagok"


class AuthorOf(models.Model):
    class Meta:
        verbose_name = "mű szerzője"
        verbose_name_plural = "művek szerzői"

    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    piece = models.ForeignKey("Piece", on_delete=models.CASCADE)
    AUTHOR_TYPES = (
        ("C", "zene"),
        ("c", "zene és szöveg"),
        ("T", "szöveg"),
        ("A", "átdolgozta"),
    )
    type = models.CharField(
        max_length=1,
        choices=AUTHOR_TYPES,
        default="C"
    )

    def __str__(self):
        return f"{self.person.get_full_name()} ({self.get_type_display()}): {self.piece.title}"


class Piece(models.Model):
    class Meta:
        verbose_name = "mű"
        verbose_name_plural = "művek"
        ordering = ['title']

    title = models.CharField("a mű címe", max_length=100)
    authors = models.ManyToManyField(
        Person,
        through='AuthorOf',
        verbose_name="szerző",
    )
    categories = models.ManyToManyField(
        "Category",
        verbose_name="kategória",
    )
    # is_whish_list = models.BooleanField(
    #     "Ez a darab kívánságlistás? Ha már szerepelt koncerten, akkor hamis.",
    #     default=False)
    comment = MarkdownxField(
        "megjegyzések", max_length=5000, blank=True,
        help_text=(
            "Bármilyen szöveg írható ide, ami segítséget ad a műhöz: miért van két kottaváltozat, "
            "felkonferáló szövegek, mások felvételeire hivatkozás. A markdown jelölőnyelv használható.")
    )

    @property
    def markdown_formatted_comment(self):
        return markdownify(self.comment)

    def __str__(self):
        authors = self.authors.all()
        author_names = "(" + ", ".join(a.family_name for a in authors) + ")" if authors else ""
        return f"{self.title} {author_names}"

    def attachements(self):
        attachements = []
        glypicon_template = '<span title="{0}" class="glyphicon glyphicon-{1}"></span>'
        if self.sheet_set.all():
            attachements.append(f"{self.sheet_set.count()} {glypicon_template.format('kotta', 'book')}")
        if self.practicerecording_set.all():
            attachements.append(f"{self.practicerecording_set.count()} {glypicon_template.format('gyakorló felvétel', 'music')}")
        if self.concertrecording_set.all():
            attachements.append(f"{self.concertrecording_set.count()} {glypicon_template.format('koncertfelvétel', 'cd')}")
        if self.comment:
            attachements.append(glypicon_template.format("megjegyzés", "comment"))
        if attachements:
            return f"({', '.join(attachements)})"
        return ""

    @staticmethod
    def search(pattern):
        """Find pieces matching a pattern."""
        words = pattern.split()

        pieces = []
        for c in Piece.objects.all():
            if all(c.is_word_in_piece_or_author(word)
                   for word in words):
                pieces.append(c)
        return pieces

    def is_word_in_piece_or_author(self, word):
        """Case and accent insensitive."""
        word_no_accent = remove_accent_lower(word)
        if word_no_accent in remove_accent_lower(self.title):
            return True
        authors = self.authors.all()
        for author in authors:
            if word_no_accent in remove_accent_lower(author.family_name) or word_no_accent in remove_accent_lower(author.given_name):
                return True
        return False

    def get_own_records(self):
        own_records = self.practicerecording_set.filter(own_record=True)
        return own_records

    def get_foreign_records(self):
        return self.practicerecording_set.filter(own_record=False)


class Category(models.Model):
    class Meta:
        verbose_name = "kategória"
        verbose_name_plural = "kategóriák"
        ordering = ['category_name']

    def __str__(self):
        return self.category_name

    category_name = models.CharField('kategória', max_length=60)
    parent = models.ManyToManyField(
        "self",
        verbose_name="szülőkategória",
        blank=True,
    )


class Sheet(models.Model):
    class Meta:
        verbose_name = "kotta"
        verbose_name_plural = "kották"

    sheet = models.FileField("fájl")
    piece = models.ForeignKey(
        Piece,
        on_delete=models.CASCADE,
        verbose_name="mű",
    )
    comment = MarkdownxField(
        "megjegyzések", max_length=5000, blank=True,
        help_text=(
            "Bármilyen szöveg írható ide, ami segítséget ad a kotta használatához. "
            "A markdown jelölőnyelv használható."
        )
    )

    @property
    def markdown_formatted_comment(self):
        return markdownify(self.comment)

    def __str__(self):
        return self.piece.title


class Event(models.Model):
    class Meta:
        verbose_name = "esemény"
        verbose_name_plural = "események"

    name = models.CharField(
        "esemény neve", max_length=200,
        help_text="Ilyen néven jelenik meg az eseménynaptárban.")
    date = models.DateField(
        'dátuma',
        help_text="Több napos eseménynél a kezdőnap dátuma.")
    is_date_estimated = models.BooleanField("A dátum bizonytalan", default=False)
    time = models.TimeField(
        'időpontja',
        blank=True, null=True,
        help_text="A kezdetének az időpontja.")
    piece = models.ManyToManyField(
        Piece,
        verbose_name="mű",
        blank=True,
    )
    is_public = models.BooleanField(
        "Publikus esemény", default=True,
        help_text="A koncertek nem publikusak, amíg nincs meghívó.")
    venue = models.ForeignKey("Venue", null=True, on_delete=models.CASCADE)
    image = models.ImageField("Meghívó képként", blank=True, null=True)
    comment = MarkdownxField(
        "megjegyzések", max_length=5000, blank=True,
        help_text=(
            "Bármilyen szöveg írható ide, amit az eseménnyel kapcsolatban hasznos tudni a kórus tagjai számára."
            " A markdown jelölőnyelv használható."
        )
    )
    recordings_directory = models.CharField(
        "hangfájlok mappája",
        max_length=40,
        blank=True,
        help_text="A könyvtár (mappa) neve, ahol a koncerten készült felvételek vannak."
    )

    @property
    def markdown_formatted_comment(self):
        return markdownify(self.comment)

    def __str__(self):
        return f"{self.name}, {self.date}"

    @property
    def is_future_event(self):
        return self.date >= datetime.now().date()


class Settlement(models.Model):
    class Meta:
        verbose_name = "település"
        verbose_name_plural = "települések"

    counties = list(enumerate((

choir/templates/choir/authors.html
{% extends "choir/search.html" %}
{% load static %}

{% block content %}
    <h1>A szerzők névsorrendben és műveik</h1>
    <a href={% url "search" %} class="btn
	    btn-warning btn-lg" role="button">Keresek a művek között</a>
    <a href={% url "categories" %} class="btn
	    btn-warning btn-lg" role="button">Mutasd kategóriák szerint!</a>

    <table class="table">
        <thead>
            <tr>
                <th>Szerző</th><th>Darabok</th>
            </tr>
        </thead>

        <tbody>
        {% for author in authors %}
            <tr>
                <td>{{author.get_bold_listed_name|safe}}</td><td>{{ author.piece_set.all| join:" &mdash; " }} </td>
            </tr>
        {%endfor%}
        </tbody>

    </table>
{% endblock content %}

choir/templates/choir/base_example.html
<!DOCTYPE html>
{% load static %}
<html lang="hu">
<head>
   <meta charset="utf-8" http-equiv="X-UA-Compatible" />
   <meta name="viewport" content="width=device-width, initial-scale=1"/>
   <title>Staccato énekegyüttes</title>


   <!--Bootstrap-->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

   <!--Custom CSS-->
   <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
   <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
   <link rel="stylesheet" href="{% static 'css/custom.css' %}">
   <link rel="shortcut icon" href="https://staccato.hu/static/favicon.ico" type="image/vnd.microsoft.icon" />
</head>

<body role="document">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
			    data-toggle="collapse" data-target="#myNavbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'choir_details' %}"><img src="{% static 'img/staccato_logo.gif' %}" width="100pt" class="img-responsive"></a>
            </div>
            <div id="myNavbar" class="collapse navbar-collapse">
                 <ul class="nav navbar-nav">
                {% block navigation %}
                     <li><a href="{% url "choir_details" %}">{% if user.is_authenticated %}Tagok{% else %}Az énekkarról{% endif %}</a></li>
                     <li><a href="{% url "search" %}">Keresés</a></li>
                     <li><a href="{% url "categories" %}">Művek</a></li>
                     <li><a href="{% url "events" %}">Események</a></li>
                 {% if user.is_authenticated %}<li><a href="{% url "logout" %}" class="btn btn-warning btn-lg" role="button">Kijelentkezés</a><li><a href="{% url "admin:index" %}">Admin</a></li>
                 {% else %}
                 <li><a href="/admin/login/?next=/events/"  class="btn btn-warning btn-lg" role="button">Bejelentkezés</a></li>{% endif %}
                {% endblock navigation %}
                 </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!--p id="demo"></p>

<script>
document.getElementById("demo").innerHTML = location.pathname;
</script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
    $(document).ready(function() {
        $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
    });
</script-->
</body>
</html>

choir/templates/choir/categories.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
 <h1>A kórus repertoárja kategóriák szerint
	csoportosítva</h1>

 <p>Az adatbázisban {{piece_number}} mű található.</p>
    <a href={% url "search" %} class="btn
	    btn-warning btn-lg" role="button">Keresek a művek között</a>
    <a href={% url "authors" %} class="btn
	    btn-warning btn-lg" role="button">Mutasd szerzők szerint!</a>

 {% for category in categories %}
  <div class="event-box">
  <h2><b>{{category.category_name|capfirst}}</b> kategória</h2>
  <p>{{category.piece_set.count}} mű</p>
  <p>{%for piece in category.piece_set.all %}<a href="{% url 'piece_detail' piece.id %}">{% include "choir/includes/piece_name.html" %}</a>{% if not forloop.last %}&mdash;{% endif %}
  {%endfor%}</p>
  </div>
 {%endfor%}
{% endblock content %}

choir/templates/choir/choir_details.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
{% if not user.is_authenticated %}<div class="jumbotron">{{choir_intro|safe}}
</div>{% endif %}
<h2>A kórus {% if user.is_authenticated %}jelenlegi és korábbi{% endif %} tagjai</h2>
<h3>Karvezető{{leaders | length |pluralize:"k"}}</h3>
{% for member in leaders %}{% include "choir/includes/member_all.html" %}{%endfor%}
<h3 style="clear:both;">Kórustagok</h3>
{% for member in members %}{% include "choir/includes/member_all.html" %}{%endfor%}
{% if user.is_authenticated %}<h3 style="clear:both;">Korábbi kórustagok</h3>
  {% for member in earlier_members %}{% include "choir/includes/member_all.html" %}{%endfor%}
{% endif %}

{% if user.is_authenticated %}
<p style="clear: both;"><a href="{% url "show_all" %}" title="Karácsonyi versek" class="btn btn-warning btn-lg" role="button">Karácsonyi versek</a></p>

<h3 style="clear:both;padding:25px 0px;">Születésnapok és névnapok</h3>
{% for month in months %}<h4>{{month | title}}</h4>
{% for member in all_members %}{% if member.birth_month == forloop.parentloop.counter %}<p> {{member.birth_day}}. {{member.name}}
<span style="color:red">születésnapja</span></p>{%endif%}{%endfor%}
{% for member in all_members %}{% if member.name_month ==  forloop.parentloop.counter %}<p> {{member.name_day}}. {{member.name}}
<span style="color:blue">névnapja</span></p>{%endif%}{%endfor%}
{%endfor%}
{%endif%}
{% endblock content %}

choir/templates/choir/event_details.html
    {% extends "choir/base.html" %}
{% load static %}

{% block content %}

<div class="event-box">
 <h2>{{event.name}}</h2>

 <p>A darabok ABC-rendben vannak.</p>
 <p>{% if event.is_date_estimated %}nincs pontos dátum, nagyjából {{ event.date|date:"Y. F" }}{% else %}
     {{ event.date|date:"Y. F j. (l)" }} {% if event.time %}{{event.time}}{% endif %}{% endif %}</p>
    {% include "choir/includes/event_details_include.html" %}

    {% if event.image %}
        <img src="{{ event.image.url }}">
    {% endif %}
</div>
{% endblock content %}

choir/templates/choir/events.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
<h1>Az események (koncertek) fordított időrendi sorrendben</h1>

<p>Az eseményeken belül a darabok ABC-rendben vannak.</p>

{% for event in events %}
    <div class="event-box">
     <h2>{{event.name}}</h2>
     <p>{% include "choir/includes/date_time.html" %}</p>
        {% if event.is_future_event %}{% include "choir/includes/event_details_include.html" %}{% endif %}
        <a href="{%  url 'event_details' event.id %}" title="Részletek" class="btn btn-warning btn-lg" role="button">Esemény részletei</a>
  </div>
{%endfor%}
{% endblock content %}

choir/templates/choir/events_public.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
<h1>Az események (koncertek) fordított időrendi sorrendben</h1>
Ha kottákat is szeretnéd látni, <a href="/admin/login/?next=/events/"  class="btn btn-warning btn-lg" role="button">jelentkezz be!</a>

{% for event in events %}
    {% if event.is_public %}
    <div class="event-box">
        <h2>{{event.name}}, {% include "choir/includes/date_time.html" %}</h2>
    {% if event.image %}
        <img src="{{ event.image.url }}">
    {% else %}
            {%for piece in  event.piece.all%}
                <p>{% include "choir/includes/piece_name.html" %}</p>
            {%endfor%}
    {% endif %}
    <a href="{%  url 'event_details' event.id %}" title="Részletek" class="btn btn-warning btn-lg" role="button">Esemény részletei</a>
    </div>
    {% endif %}
{%endfor%}
{% endblock content %}

choir/templates/choir/index.html
{%  extends "choir/base.html" %}
{% load static %}

{% block content %}
        <p class="lead">Ez egy kórus honlapja. Fejlesztés alatt áll.</p>
{% endblock content %}

choir/templates/choir/piece_detail.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
    <h1>{{ piece.title }}</b></h1>

{% if  piece.authorof_set.all %}
    <h2>Szerzők</h2>
{% for authorof in piece.authorof_set.all %}
    <p><b>{{ authorof.person.get_full_name }}</b>, {{authorof.get_type_display}}</p>
{%endfor%}
{% endif %}

{% if user.is_authenticated %}
    {% include "choir/includes/piece_info_for_members_only.html" %}
{% else %}
<p>Ha kottákat és szólamfelvételeket is szeretnéd látni, <a href="/admin/login/?next={{request.path}}"  class="btn btn-warning btn-lg" role="button">jelentkezz be!</a>
{% endif %}

<h2>Ezeken az eseményeken szerepelt vagy fog szerepelni</h2>

{% if piece.event_set.all %}
    {% for event in piece.event_set.all %}
      {% if user.is_authenticated or event.is_public %}
        <p>
            <a href="{%  url 'event_details' event.id %}" title="{{sheet.name}}" class="btn btn-warning btn-lg" role="button">Esemény részletei</a> {{event.name}},
            {% if event.is_date_estimated %}nincs pontos dátum, nagyjából {{ event.date|date:"Y. F j." }}{% else %} {{ event.date|date:"Y. F j. (l)" }} {% if event.time %}{{event.time}}{% endif %}{% endif %} {% include "choir/includes/recordings_directory_include.html" %}</p>
      {% endif %}
    {% endfor %}
{% else %}
    <p>Az adatbázis szerint még egyetlen eseményen sem énekeltük.</p>
{% endif %}
{% endblock content %}

choir/templates/choir/search.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
    <p class="lead">Keresés</p>
    <div class="text-center">
      <h1>{% block header_title %}{% endblock %}</h1>

      <form method="POST" action="{% block form_action %}{% endblock %}">
        <input name="pattern" id="id_new_item" class="form-control
	input-lg" placeholder="Címben vagy szerzőnévben szereplő szavak részletei" autofocus/>
        {% csrf_token %}
      </form>
    </div>

    <p class="lead" style="margin-top:15px;">Segítség és tippek</p>
    <ul>
	<li><b style="color:red;">Kis és nagy betű nem számít.</b>
	<li><b style="color:red;">Ékezet nem számít.</b> <b>Példa:</b> Ha a Gøta című művet keresed, <b>gota</b> megtalálja. De kereshetsz szerző szerint is. <b>part</b> megtalálja az összes Pärt-darabot.
	<li>A kereső a beírt szavakat szóköz mentén részekre bontja, és mindegyiket keresi a címben és a szerzőben. Ha minden szórészlet megtalálható a címben vagy a szerző teljes nevében, akkor fogja felsorolni a találatot.
	<li>Kodály: Adventi énekét megtalálod így: <b>advent</b>
	<li>Whitacre: Alleluja művét megtalálod így: <b>whit alle</b>.  (Mindkét részletnek benne kell lennie, így nem találja meg a White Christmas-t)
	<li>Ha az <b>all</b> szövegre keresel, akkor megtalálja például az összes <b>All</b>eluiát, T<b>all</b>is műveit, és a V<b>all</b>on szerenádot. De a K<b>áll</b>ai kettőst is.
    </ul>

    <p class="lead">{{list_title}}</p>

    {% if pattern %}
    {% if pieces %}
        {% for piece in pieces %}
	<p>
	<a href={% url "piece_detail" piece.id %} class="btn
	    btn-warning btn-lg" role="button">Mű részletei</a>
	{% include "choir/includes/piece_name.html" %}</p>
        {%endfor%}
    {% else %}
	<p>Nem találtam illeszkedő művet. Remélem, módosított kereséssel megtalálod a keresett művet!</p>
    {% endif  %}
    {% endif  %}
{% endblock content %}

choir/templates/choir/upload_record.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
    <div class="text-left">
    <h1>Gyakorló hangfelvétel feltöltése – <b>{{ piece.title }}</b></h1>

    <p>Ide tartoznak a gyakrlásra szánt külső felvételek is (például
    Youtube-videóból kiszedett hangsávok is) csak ott a saját felvétel mező
    mellől ki kell venni a pipát.</p>

      <form method="POST" action="{% block form_action %}{% endblock %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Mehet">
      </form>
    </div>

    <p class="lead">{{list_title}}</p>

    {% if piece.practicingrecord_set.count %}
	<p> A műhöz már tartozik legalább egy gyakorló felvétel: </p>
        {% for record in piece.practicingrecord_set.all %}
	<p>
    <b>{{record.audio_file.name}}</b> {{record.audio_file.size|filesizeformat}},
    {% if record.own_record %} saját felvétel {% else %} külső felvétel{% endif %}
	</p>
        {%endfor%}
    {% else %}
    {% endif  %}

{% endblock content %}

choir/templates/choir/upload_sheet.html
{% extends "choir/base.html" %}
{% load static %}

{% block content %}
    <div class="text-left">
    <h1>Kotta feltöltése műhöz – <b>{{ piece.title }}</b></h1>

      <form method="POST" action="{% block form_action %}{% endblock %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Mehet">
      </form>
    </div>

    <p class="lead">{{list_title}}</p>

    {% if piece.sheet_set.count %}
	<p> A műhöz már tartozik legalább egy kotta: </p>
        {% for sheet in piece.sheet_set.all %}
	<p>
    <b>{{sheet.sheet.name}}</b> {{sheet.sheet.size|filesizeformat}}
	</p>
        {%endfor%}
    {% else %}
    {% endif  %}

{% endblock content %}