choir/urls.py
from django.urls import re_path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(pattern_name='events')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
    # re_path(r'^sheets/$', views.sheets, name='sheets'),
    re_path(r'^events/$', views.events, name='events'),
    re_path(r'^wishlist/$', views.wishlist, name='wishlist'),
    re_path(r'^events/(\d+)$', views.event_details, name='event_details'),
    re_path(r'^choir/$', views.choir_details, name='choir_details'),

    re_path(r'^pieces/$', views.search, name='search'),
    re_path(r'^pieces/authors/$', views.authors, name='authors'),
    re_path(r'^pieces/categories/$', views.categories, name='categories'),
    re_path(r'^pieces/(\d+)$', views.piece_detail, name='piece_detail'),

# Depreciated
    re_path(r'^repertoire/search$', views.search, name='repertoire_search'),
    re_path(r'^repertoire/authors/$', views.authors, name='repertoire_authors'),
    re_path(r'^repertoire/categories/$', views.categories, name='repertoire_categories'),
    re_path(r'^repertoire/(\d+)$', views.piece_detail, name='repertoire_piece_detail'),

#     re_path(r'^pieces/(\d+)/upload/main$', views.upload_main, name='upload_main'),
#     re_path(r'^pieces/(\d+)/upload/voice_type/result$', views.upload_voice_type_result, name='upload_voice_type_result'),
#     re_path(r'^pieces/(\d+)/upload/concert$', views.upload_sheet, name='upload_concert'),
     re_path(r'^pieces/(\d+)/upload/practicing_record$', views.upload_practice_recording, name='upload_practice_recording'),
     re_path(r'^pieces/(\d+)/upload/sheet$', views.upload_sheet, name='upload_sheet'),
]

djangochoir/urls.py
"""djangochoir URL Configuration
"""
from django.urls import re_path, include
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^markdownx/', include('markdownx.urls')),
    re_path(r'^xmas/', include('christmas.urls')),
    re_path(r'^', include('choir.urls')),
]

choir/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from datetime import datetime
import unicodedata


def remove_accent_lower(text: str) -> str:
    return unicodedata.normalize('NFKD', text).lower().replace("ø", "o").encode('ASCII', 'ignore').decode('ASCII')


MONTH_NAMES = [
    '', 'január', 'február', 'március', 'április', 'május', 'június',
    'július', 'augusztus', 'szeptember', 'október', 'november', 'december'
]


# import calendar
# MONTH_NAMES = calendar.month_name


class Person(models.Model):
    class Meta:
        verbose_name = "személy"
        verbose_name_plural = "személyek"
        ordering = ["family_name"]

    suffix = models.CharField("előtag", max_length=70, blank=True, default="")
    family_name = models.CharField("családnév", max_length=70)
    given_name = models.CharField("keresztnév", max_length=70)
    NAME_ORDERS = (
        (0, "Western"),
        (1, "Eastern"),
    )
    name_order = models.IntegerField(
        choices=NAME_ORDERS,
    )

    def get_full_name(self):
        if self.name_order == 0:
            first = self.given_name
            second = self.family_name
        elif self.name_order == 1:
            first = self.family_name
            second = self.given_name
        name = f"{first} {second}"
        if self.suffix:
            name = self.suffix + " " + name
        return name

    def get_listed_name(self, bold_family=False):
        if bold_family:
            format_string = "<b>{0.family_name}</b>, {0.given_name}"
        else:
            format_string = "{0.family_name}, {0.given_name}"

        if self.suffix:
            format_string = "{0.suffix} " + format_string
        return format_string.format(self)

    def get_bold_listed_name(self):
        return self.get_listed_name(bold_family=True)

    def __str__(self):
        return self.get_listed_name()


class Member(models.Model):
    DAY_CHOICES = [(i, i) for i in range(1, 32)]
    MONTH_CHOICES = [(i, MONTH_NAMES[i]) for i in range(1, 13)]
    PARTS = (
        ("S", "szoprán"),
        ("A", "alt"),
        ("T", "tenor"),
        ("B", "basszus"),
    )
    name = models.CharField("Név", max_length=200)

    email = models.EmailField("Email", blank=True, null=True)
    phone = models.CharField("Telefonszám", max_length=40, blank=True, null=True)

    birth_month = models.IntegerField("Születési hónap", choices=MONTH_CHOICES)
    birth_day = models.IntegerField("Születési nap", choices=DAY_CHOICES)

    name_month = models.IntegerField("Névnap hónapja", choices=MONTH_CHOICES)
    name_day = models.IntegerField("Névnap napja", choices=DAY_CHOICES)

    part = models.CharField("Szólam", max_length=1, choices=PARTS)

    public_notes = models.TextField("Szöveg a honlapra", max_length=250, blank=True)

    address = models.CharField("Cím", max_length=200)

    image = models.ImageField("Arckép honlapra", blank=True, null=True)

    is_leader = models.BooleanField("Karvezető?", default=False)

    is_active = models.BooleanField(
        "Aktív",
        default=True,
        help_text="Az aktív tagok jelennek meg a bemutatkozóoldalon."
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "kórustag"
        verbose_name_plural = "kórustagok"


class AuthorOf(models.Model):
    class Meta:
        verbose_name = "mű szerzője"
        verbose_name_plural = "művek szerzői"

    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    piece = models.ForeignKey("Piece", on_delete=models.CASCADE)
    AUTHOR_TYPES = (
        ("C", "zene"),
        ("c", "zene és szöveg"),
        ("T", "szöveg"),
        ("A", "átdolgozta"),
    )
    type = models.CharField(
        max_length=1,
        choices=AUTHOR_TYPES,
        default="C"
    )

    def __str__(self):
        return f"{self.person.get_full_name()} ({self.get_type_display()}): {self.piece.title}"


class Piece(models.Model):
    class Meta:
        verbose_name = "mű"
        verbose_name_plural = "művek"
        ordering = ['title']

    title = models.CharField("a mű címe", max_length=100)
    authors = models.ManyToManyField(
        Person,
        through='AuthorOf',
        verbose_name="szerző",
    )
    categories = models.ManyToManyField(
        "Category",
        verbose_name="kategória",
    )
    # is_whish_list = models.BooleanField(
    #     "Ez a darab kívánságlistás? Ha már szerepelt koncerten, akkor hamis.",
    #     default=False)
    comment = MarkdownxField(
        "megjegyzések", max_length=5000, blank=True,
        help_text=(
            "Bármilyen szöveg írható ide, ami segítséget ad a műhöz: miért van két kottaváltozat, "
            "felkonferáló szövegek, mások felvételeire hivatkozás. A markdown jelölőnyelv használható.")
    )

    @property
    def markdown_formatted_comment(self):
        return markdownify(self.comment)

    def __str__(self):
        authors = self.authors.all()
        author_names = "(" + ", ".join(a.family_name for a in authors) + ")" if authors else ""
        return f"{self.title} {author_names}"

    def attachements(self):
        attachements = []
        glypicon_template = '<span title="{0}" class="glyphicon glyphicon-{1}"></span>'
        if self.sheet_set.all():
            attachements.append(f"{self.sheet_set.count()} {glypicon_template.format('kotta', 'book')}")
        if self.practicerecording_set.all():
            attachements.append(f"{self.practicerecording_set.count()} {glypicon_template.format('gyakorló felvétel', 'music')}")
        if self.concertrecording_set.all():
            attachements.append(f"{self.concertrecording_set.count()} {glypicon_template.format('koncertfelvétel', 'cd')}")
        if self.comment:
            attachements.append(glypicon_template.format("megjegyzés", "comment"))
        if attachements:
            return f"({', '.join(attachements)})"
        return ""

    @staticmethod
    def search(pattern):
        """Find pieces matching a pattern."""
        words = pattern.split()

        pieces = []
        for c in Piece.objects.all():
            if all(c.is_word_in_piece_or_author(word)
                   for word in words):
                pieces.append(c)
        return pieces

    def is_word_in_piece_or_author(self, word):
        """Case and accent insensitive."""
        word_no_accent = remove_accent_lower(word)
        if word_no_accent in remove_accent_lower(self.title):
            return True
        authors = self.authors.all()
        for author in authors:
            if word_no_accent in remove_accent_lower(author.family_name) or word_no_accent in remove_accent_lower(author.given_name):
                return True
        return False

    def get_own_records(self):
        own_records = self.practicerecording_set.filter(own_record=True)
        return own_records

    def get_foreign_records(self):
        return self.practicerecording_set.filter(own_record=False)


class Category(models.Model):
    class Meta:
        verbose_name = "kategória"
        verbose_name_plural = "kategóriák"
        ordering = ['category_name']

    def __str__(self):
        return self.category_name

    category_name = models.CharField('kategória', max_length=60)
    parent = models.ManyToManyField(
        "self",
        verbose_name="szülőkategória",
        blank=True,
    )


class Sheet(models.Model):
    class Meta:
        verbose_name = "kotta"
        verbose_name_plural = "kották"

    sheet = models.FileField("fájl")
    piece = models.ForeignKey(
        Piece,
        on_delete=models.CASCADE,
        verbose_name="mű",
    )
    comment = MarkdownxField(
        "megjegyzések", max_length=5000, blank=True,
        help_text=(
            "Bármilyen szöveg írható ide, ami segítséget ad a kotta használatához. "
            "A markdown jelölőnyelv használható."
        )
    )

    @property
    def markdown_formatted_comment(self):
        return markdownify(self.comment)

    def __str__(self):
        return self.piece.title


class Event(models.Model):
    class Meta:
        verbose_name = "esemény"
        verbose_name_plural = "események"

    name = models.CharField(
        "esemény neve", max_length=200,
        help_text="Ilyen néven jelenik meg az eseménynaptárban.")
    date = models.DateField(
        'dátuma',
        help_text="Több napos eseménynél a kezdőnap dátuma.")
    is_date_estimated = models.BooleanField("A dátum bizonytalan", default=False)
    time = models.TimeField(
        'időpontja',
        blank=True, null=True,
        help_text="A kezdetének az időpontja.")
    piece = models.ManyToManyField(
        Piece,
        verbose_name="mű",
        blank=True,
    )
    is_public = models.BooleanField(
        "Publikus esemény", default=True,
        help_text="A koncertek nem publikusak, amíg nincs meghívó.")
    venue = models.ForeignKey("Venue", null=True, on_delete=models.CASCADE)
    image = models.ImageField("Meghívó képként", blank=True, null=True)
    comment = MarkdownxField(
        "megjegyzések", max_length=5000, blank=True,
        help_text=(
            "Bármilyen szöveg írható ide, amit az eseménnyel kapcsolatban hasznos tudni a kórus tagjai számára."
            " A markdown jelölőnyelv használható."
        )
    )
    recordings_directory = models.CharField(
        "hangfájlok mappája",
        max_length=40,
        blank=True,
        help_text="A könyvtár (mappa) neve, ahol a koncerten készült felvételek vannak."
    )

    @property
    def markdown_formatted_comment(self):
        return markdownify(self.comment)

    def __str__(self):
        return f"{self.name}, {self.date}"

    @property
    def is_future_event(self):
        return self.date >= datetime.now().date()


class Settlement(models.Model):
    class Meta:
        verbose_name = "település"
        verbose_name_plural = "települések"

    counties = list(enumerate((

choir/templates/choir/includes/concertrecord_details.html
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3" style="margin: 2px; background-color:#fee; padding: 5px 15px;">
<a href="{{record.audio_file.url}}" title="{{record.audio_file.name}}"
     class="btn btn-warning btn-lg"
     role="button">{{record.event.date}}</a> <b>{{record.event.name}}</b> {% if record.comment %}{{record.markdown_formatted_comment | safe}}{% endif %} 
</div>

choir/templates/choir/includes/date_time.html
{% if event.is_date_estimated %}nincs pontos dátum, nagyjából {{event.date|date:"Y. F j." }}{% else %}
{{ event.date|date:"Y. F j. (l)" }} {% if event.time %}{{event.time}}{% endif %}{% endif %}

choir/templates/choir/includes/event_details_include.html
<p>Helyszín: {{ event.venue.name }}
     ({% if event.venue.zip_code%}{{event.venue.zip_code}} {%endif%}{{event.venue.telepules.name}}{% if event.venue.address%}, {{event.venue.address}}{%endif%})</p>
     {%for piece in  event.piece.all%}
         <p><a href="{% url 'piece_detail' piece.id %}" title="{{piece.title}}" class="btn btn-warning btn-lg" role="button">Részletek</a>
     {% if user.is_authenticated %}{{ piece.attachements|safe }}{%endif%}
     {% include "choir/includes/piece_name.html" %}</p>
     {%endfor%}

<p>{% include "choir/includes/recordings_directory_include.html" %}</p>
{% if event.comment and user.is_authenticated %}<h2>Megjegyzések:</h2>{{ event.markdown_formatted_comment|safe}}{% endif %}

choir/templates/choir/includes/member_all.html
<div class="well col-xs-12 col-sm-6 col-md-6 col-lg-4" style="margin-bottom:0px;font-size:120%;padding: 5px 15px;height:17em;border:solid white 5px"><p><b>{{ member.name }}</b> {{ member.get_part_display }}</p>{% if user.is_authenticated %}{% include "choir/includes/member_restricted.html" %}{% else %}{% include "choir/includes/member_public.html" %}{% endif %}</div>

choir/templates/choir/includes/member_public.html
<img style="max-height:10em;" src={% if member.part in "TB" %}"https://staccato.hu/media/icons/Man-Icon.png"{% else %}"https://staccato.hu/media/icons/Women-Icon-b.png"{% endif %}>

choir/templates/choir/includes/member_restricted.html
<p>{{ member.address }}</p>
<p>Születésnap: {{ member.get_birth_month_display }} {{ member.birth_day }}.</p>
<p>Névnap: {{ member.get_name_month_display }} {{ member.name_day }}.</p>
<p><span class="glyphicon glyphicon-envelope"></span> {{ member.email }}</p>
<p><span class="glyphicon glyphicon-phone"></span> {{ member.phone }}</p>
<p><a href="{% url "show_to_person" member.id %}" title="Karácsonyi versek" class="btn btn-warning btn-lg" role="button">Versek neki</a>&nbsp;<a href="{% url "show_author" member.id %}" title="Karácsonyi versek" class="btn btn-warning btn-lg" role="button">Tőle <span class="glyphicon glyphicon-tree-conifer"></a></p>

choir/templates/choir/includes/piece_info_for_members_only.html
<h2>Kották</h2>
{% if piece.sheet_set.count %}
{%for sheet in piece.sheet_set.all%}<p><a href="{{sheet.sheet.url}}" title="{{sheet.sheet.name}}" class="btn btn-warning btn-lg" role="button">Kotta</a></p> {{sheet.markdown_formatted_comment |safe}}{%endfor%}
{% else %}
    <p>Nincs még kotta feltöltve ehhez a műhöz!</p>
{% endif %}

<a href="{% url "upload_sheet" piece.id %}" title="Új kotta feltöltése" class="btn btn-warning btn-lg" role="button"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Kotta feltöltése</a>


<h2>Saját gyakorlófelvételek</h2>
{% if piece.get_own_records %}
<div class="container">
<div class="row">
{% for record in piece.get_own_records %}
  {% include "choir/includes/record_details.html" %}
{% endfor %}
</div>
</div>
{% else %}
    <p>Nincs még gyakorlófelvétel feltöltve ehhez a műhöz!</p>
{% endif %}

<a href="{% url "upload_practice_recording" piece.id %}" title="Új gyakorlófelvétel feltöltése" class="btn btn-warning btn-lg" role="button"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Gyakorlófelvétel feltöltése</a>


<h2>Külső felvételek (pl. YouTube-ról lementett hang)</h2>
{% if piece.get_foreign_records %}
<div class="container">
<div class="row">
{% for record in piece.get_foreign_records %}
  {% include "choir/includes/record_details.html" %}
{% endfor %}
</div>
</div>
{% else %}
    <p>Nincs még külső felvétel feltöltve ehhez a műhöz!</p>
{% endif %}

<!-- Not used yet.
<h2>Ezek a koncertfelvételek vannak az adatbázisunkban</h2>

{% if piece.concertrecording_set.all %}
<div class="container">
<div class="row">
{% for record in piece.concertrecording_set.all %}
  {% include "choir/includes/concertrecord_details.html" %}
{% endfor %}
</div>
</div>
{% else %}
    <p>Nincs még koncertfelvétel feltöltve ehhez a műhöz!</p>
{% endif %}
-->

{% if piece.comment %}<h2>Megjegyzések</h2> {{ piece.markdown_formatted_comment|safe}}{% endif %}

choir/templates/choir/includes/piece_name.html
<b>{{piece.title}}</b> {% if piece.authors.count %}({%for author in piece.authors.all %}{{author.family_name}}{% if not forloop.last %}, {% endif %}{%endfor%}){%endif%}

choir/templates/choir/includes/record_details.html
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3" style="margin: 2px; background-color:#fee; padding: 5px 15px;">
<a href="{{record.audio_file.url}}" title="{{record.audio_file.name}}"
     class="btn btn-warning btn-lg"
 role="button">{{record.get_part_display.capitalize}}</a> {% if record.comment %}{{record.markdown_formatted_comment | safe}}{% endif %}
</div>

choir/templates/choir/includes/recordings_directory_include.html
{% if event.recordings_directory %}<a href="http://staccato.pyedu.hu/media/concert_recording/{{ event.recordings_directory }}" title="Hangfelvételek" class="btn btn-warning btn-lg" role="button">Hangfelvételek</a>{% else %}Nincsen hangfelvétel{% endif %}